### ISSUE TITLE
Home-assistant configuration problem

### ISSUE THREAD

**Issue by fosselius** [ChristianKuehnel/bimmer_connected#34]
Hi, 
I just tried to configure the Home Assistant component and received the error message "Invalid config for [bmw_connected_drive]: [name] is invalid option for [bmw_connected_drive]

What am I doing wrong when configuring? What am I supposed to put as name?

**Comment by gerard33** [comment]
You have to remove the `name` line completely. See a working example below.
A change for the documentation is on it’s way.

```yaml
 # Example configuration.yaml entry
 bmw_connected_drive:
   mycar:
     username: USERNAME_BMW_CONNECTED_DRIVE
     password: PASSWORD_BMW_CONNECTED_DRIVE
     country: COUNTRY_BMW_CONNECTED_DRIVE
```
